name: Compile news items into CHANGELOG.rst

on:
  workflow_call:
    inputs:
      update_changelog_result:
        description: 'Whether the previous update-changelog job succeeded'
        required: true
        type: string

jobs:
  delete-create-new-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Fail delete-create-new-tag job if CHANGELOG update failed
        run: |
          if [ "${{ needs.update-changelog.result }}" == 'success' ]; then
            echo "Ready to delete and create new tag containing the latest CHANGELOG.rst update in the main branch..."
          else
            echo "Previous update-changelog job failed; exiting..."
            exit 1
          fi
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Delete the tag
        run: |
          git fetch --tags
          git tag -d "${{ github.ref_name }}"
          git push origin ":${{ github.ref_name }}"
      - name: Create a new tag (Expect commit SHA to match with that of main branch)
        run: |
          git tag "${{ github.ref_name }}"
          git push origin "${{ github.ref_name }}"