name: Pre-release on GitHub

on:
  workflow_call:

jobs:
  github-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GH release notes for pre-release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
