name: Release on GitHub

on:
  workflow_call:
    inputs:
      delete-create-new-tag-result:
        description: 'Whether the previous delete-create-new-tag job succeeded'
        required: true
        type: string

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fail github-release job if CHANGELOG update failed
        run: |
          if [ "${{ inputs.delete-create-new-tag-result }}" == 'success' ]; then
            echo "Ready to release on GitHub..."
          else
            echo "Previous update-changelog job failed; exiting..."
            exit 1
          fi
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Generate GH release notes for release
        run: |
          wget https://raw.githubusercontent.com/scikit-package/release-scripts/v0/.github/workflows/get-latest-changelog.py
          python get-latest-changelog.py "${{ github.ref_name }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true