name: Release on PyPI

on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        description: 'PyPI token'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '**/*'
          path: dist
          merge-multiple: true

      - name: Setup Python for PyPI upload
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Twine
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/* --verbose
