name: Release on GitHub with tag pushed to remote repository

on:
  workflow_call:
    inputs:
      maintainer_github_username:
        description: GitHub username authorized to start GitHub/PyPI release'
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  tag-privilege-check:
    uses: ./.github/workflows/_release_tag_privilege_check.yml
    with:
      maintainer_github_username: ${{ inputs.maintainer_github_username }}

  update-changelog:
    uses: ./.github/workflows/_update_changelog.yml
    needs: [tag-privilege-check]
    if: "always() && !contains(github.ref, 'rc')"

  delete-create-new-tag:
    # Please see the comments provided in _build-whel-release-upload.yml
    uses: ./.github/workflows/_delete_create_tag.yml
    needs: [update-changelog]
    if: "always() && !contains(github.ref, 'rc')"
    with:
      update_changelog_result: ${{ needs.update-changelog.result }}

  github-pre-release:
    needs: [tag-privilege-check]
    if: "always() && contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Generate GH release notes for pre-release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  github-release:
    needs: [delete-create-new-tag]
    if: "always() && !contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Fail github-release job if CHANGELOG update failed
        run: |
          if [ "${{ needs.delete-create-new-tag.result }}" == 'success' ]; then
            echo "Ready to release on GitHub..."
          else
            echo "Previous update-changelog job failed; exiting..."
            exit 1
          fi
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Generate GH release notes for release
        run: |
          wget https://raw.githubusercontent.com/scikit-package/release-scripts/v0/.github/workflows/get-latest-changelog.py
          python get-latest-changelog.py "${{ github.ref_name }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

