name: Upload to Codecov

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: 'Codecov token'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
